@startuml
skinparam ClassFontName Arial
skinparam ClassFontSize 12
skinparam ClassAttributeIconSize 0
skinparam ClassBackgroundColor #EEF9EE
skinparam ClassBorderColor #6AA84F
skinparam ArrowColor #6A6A6A
skinparam ArrowThickness 1
hide empty methods
top to bottom direction

class "RSAllergyIntolerance" {
  code : — [0..1]
  patient : — [1..1]
  patient : Reference(RSPatient)
}
class "AllergyIntolerance"
class "RSPatient" {
  name : — [1..*]
  name.family : — [0..1]
  name.given : — [1..*]
  birthDate : — [0..1]
  telecom : — [0..*]
  identifier : — [0..*]
  address : — [0..*]
  address.line : — [0..*]
  address.extension : — [0..*]
}
class "RSBundleEMS" {
  type : — [1..1]
  entry : — [1..*]
  entry.resource : — [1..1]
  entry[patient].resource : RSPatient
  entry[encounter].resource : RSEncounter
  entry[location].resource : RSLocation
  entry[observationDateReceived].resource : rs
  entry[observationTimeEnroute].resource : rs
  entry[observationTimeOnScene].resource : rs
  entry[observationTimeDeparted].resource : rs
  entry[observationTimeHospitalArrival].resource : rs
  entry[observationTimeStationArrival].resource : rs
  entry[observationVitals].resource : rs
  entry[observationGCS].resource : rs
  entry[observationInjuryDatetime].resource : rs
  entry[observationInjuryIntent].resource : rs
  entry[observationTransportFlag].resource : rs
  entry[observationModeOfTransport].resource : rs
  entry[observationTriage].resource : rs
  entry[observationCollisionType].resource : rs
  entry[observationVehicleUsed].resource : rs
  entry[observationRunReportComments].resource : rs
  entry[observationClinicalRemarks].resource : rs
  entry[observationVehicles].resource : rs
  entry[observationInjuries].resource : rs
  entry[observationExternalCauses].resource : rs
  entry[document].resource : RSDocumentReference
  entry[task].resource : RSTask
  entry[serviceRequest].resource : RSServiceRequest
  entry[procedure].resource : RSProcedure
  entry[claim].resource : rs
}
class "Bundle"
class "RSBundleONEISS" {
  type : — [1..1]
  entry : — [1..*]
  entry.resource : — [1..1]
  entry[patient].resource : RSPatient
  entry[encounter].resource : RSEncounter
  entry[conditionInitial].resource : rs
  entry[conditionFinal].resource : rs
  entry[observationVitals].resource : rs
  entry[observationClinical].resource : rs
  entry[observationIncident].resource : rs
  entry[document].resource : RSDocumentReference
  entry[serviceRequest].resource : RSServiceRequest
  entry[procedure].resource : RSProcedure
}
class "RSClaim" {
  patient : — [1..1]
  patient : Reference(RSPatient)
  total : — [0..1]
}
class "Claim"
class "RSCondition" {
  code : — [1..1]
  subject : — [1..1]
  subject : Reference(RSPatient)
  encounter : — [0..1]
  encounter : Reference(RSEncounter)
  onset[x] : — [0..1]
  abatement[x] : — [0..1]
}
class "Condition"
class "RSEncounter" {
  status : — [1..1]
  class : — [1..1]
  identifier : — [1..*]
  period.start : — [1..1]
  serviceProvider : — [0..1]
  serviceProvider : Reference(RSOrganization)
  participant : — [0..*]
  hospitalization.dischargeDisposition : — [0..1]
  hospitalization.destination : — [0..1]
  identifier : — [0..1]
  identifier[incidentNumber].type : — [1..1]
  identifier[incidentNumber].type.coding : — [1..1]
  identifier[hospitalCaseNo].type : — [1..1]
  identifier[hospitalCaseNo].type.coding : — [1..1]
  hospitalization.origin : — [0..1]
  hospitalization.origin : Reference(RSOrganization)
  participant : — [0..1]
  participant[receivedBy].individual : — [0..1]
  participant[receivedBy].individual : Reference(PHCorePractitioner)
  participant[teamLeader].individual : — [0..1]
  participant[teamLeader].individual : Reference(PHCorePractitioner)
  participant[treatmentOfficer].individual : — [0..1]
  participant[treatmentOfficer].individual : Reference(PHCorePractitioner)
  participant[transportOfficer].individual : — [0..1]
  participant[transportOfficer].individual : Reference(PHCorePractitioner)
  participant[assistant].individual : — [0..1]
  participant[assistant].individual : Reference(PHCorePractitioner)
}
class "RSDocumentReference" {
  status : — [1..1]
  type : — [0..1]
  subject : — [0..1]
  subject : Reference(RSPatient)
  context.encounter : — [0..1]
  context.encounter : Reference(RSEncounter)
  content : — [1..*]
  content.attachment.url : — [1..1]
  content.format : — [0..1]
}
class "DocumentReference"
class "PHCoreEncounter"
class "RSOrganization" {
  active : — [0..1]
  type : — [0..*]
  name : — [1..1]
  identifier : — [0..*]
  telecom : — [0..*]
  address : — [0..*]
}
class "PHCorePractitioner"
class "RSLocation" {
  name : — [0..1]
  address : — [0..1]
  address.line : — [0..*]
  address.extension : — [0..*]
  position.longitude : — [1..1]
  position.latitude : — [1..1]
}
class "PHCoreLocation"
class "RSMedicationStatement" {
  medication[x] : — [1..1]
  subject : — [1..1]
  subject : Reference(RSPatient)
  effective[x] : — [0..1]
}
class "MedicationStatement"
class "RSObservation" {
  status : — [1..1]
  subject : — [1..1]
  subject : Reference(RSPatient)
  code : — [1..1]
  encounter : — [0..1]
  encounter : Reference(RSEncounter)
  effective[x] : — [0..1]
  performer : — [0..*]
  value[x] : — [0..1]
}
class "PHCoreObservation"
class "PHCoreOrganization"
class "RSHealthcareService" {
  active : — [0..1]
  type : — [0..*]
  name : — [0..1]
  identifier : — [0..*]
  telecom : — [0..*]
  providedBy : — [1..1]
  providedBy : Reference(RSOrganization)
  location : — [0..*]
  location : Reference(RSLocation)
  coverageArea : — [0..*]
}
class "HealthcareService"
class "PHCorePatient"
class "RSProcedure" {
  status : — [1..1]
  code : — [0..1]
  subject : — [1..1]
  subject : Reference(RSPatient)
  encounter : — [0..1]
  encounter : Reference(RSEncounter)
  performer : — [0..*]
  performer.actor : Reference(PHCorePractitioner)
  note : — [0..*]
}
class "PHCoreProcedure"
class "RSServiceRequest" {
  status : — [1..1]
  occurrenceDateTime : — [0..1]
  supportingInfo : — [0..*]
  supportingInfo : Reference(RSHealthcareService | RSOrganization | PHCoreOrganization | PHCorePractitioner)
  requester : — [0..1]
  requester : Reference(PHCorePractitioner)
  code : — [1..1]
  code.coding : — [1..1]
  subject : — [1..1]
  subject : Reference(RSPatient)
  encounter : — [0..1]
  encounter : Reference(RSEncounter)
}
class "ServiceRequest"
class "RSTask" {
  status : — [1..1]
  executionPeriod : — [0..1]
  note : — [0..*]
  for : — [0..1]
  for : Reference(RSPatient)
  focus : — [0..1]
  input : — [0..*]
  output : — [0..*]
}
class "Task"
class "Obs (RS profiles)" {
  "Road Safety Observation - Respiratory Rate" : Profile
  "Road Safety Observation - Pulse Rate" : Profile
  "Road Safety Observation - Blood Pressure" : Profile
  "Road Safety Observation - Body Temperature" : Profile
  "Road Safety Observation - Level of Consciousness (AVPU)" : Profile
  "Road Safety Observation - Pupils" : Profile
  "Road Safety Observation - Cyanosis" : Profile
  "Road Safety Observation - Glasgow Coma Scale" : Profile
  "Road Safety Observation - Respiratory Rhythm" : Profile
  "Road Safety Observation - Breath Sounds" : Profile
  "Road Safety Observation - Pulse Rhythm" : Profile
  "Road Safety Observation - Pulse Quality" : Profile
  "Road Safety Observation - Date/Time Received by EMS" : Profile
  "Road Safety Observation - Time Enroute" : Profile
  "Road Safety Observation - Time On Scene" : Profile
  "Road Safety Observation - Time Departed Scene" : Profile
  "Road Safety Observation - Time of Hospital Arrival" : Profile
  "Road Safety Observation - Time of Emergency Station Arrival" : Profile
  "Road Safety Observation - Date/Time of Injury" : Profile
  "Road Safety Observation - Injury Intent" : Profile
  "Road Safety Observation - Transport/Vehicular Accident (flag)" : Profile
  "Road Safety Observation - Mode of Transport to Facility" : Profile
  "Road Safety Observation - Triage Priority" : Profile
  "Road Safety Observation - Priority Level (Urgency)" : Profile
  "Road Safety Observation - Place of Occurrence" : Profile
  "Road Safety Observation - Activity at Time of Incident" : Profile
  "Road Safety Observation - Collision vs Non-Collision" : Profile
  "Road Safety Observation - Patient's Vehicle" : Profile
  "Road Safety Observation - Other Vehicle/Object Involved" : Profile
  "Road Safety Observation - Position of Patient" : Profile
  "Road Safety Observation - How Many Vehicles Involved" : Profile
  "Road Safety Observation - How Many Patients Involved" : Profile
  "Road Safety Observation - Collision Type" : Profile
  "Road Safety Observation - Presence of Traffic Investigator" : Profile
  "Road Safety Observation - Other Risk Factors" : Profile
  "Road Safety Observation - Safety Accessories" : Profile
  "Road Safety Observation - Reported Complaint" : Profile
  "Road Safety Observation - Call Source" : Profile
  "Road Safety Observation - External Cause: Bites/Stings" : Profile
  "Road Safety Observation - External Cause: Burns" : Profile
  "Road Safety Observation - External Cause: Chemical/Substance" : Profile
  "Road Safety Observation - External Cause: Contact with Sharp Object" : Profile
  "Road Safety Observation - External Cause: Drowning" : Profile
  "Road Safety Observation - External Cause: Exposure to Forces of Nature" : Profile
  "Road Safety Observation - External Cause: Fall" : Profile
  "Road Safety Observation - External Cause: Firecracker" : Profile
  "Road Safety Observation - External Cause: Gunshot" : Profile
  "Road Safety Observation - External Cause: Hanging/Strangulation" : Profile
  "Road Safety Observation - External Cause: Mauling/Assault" : Profile
  "Road Safety Observation - External Cause: Sexual Assault/Abuse/Rape (Alleged)" : Profile
  "Road Safety Observation - External Cause: Other" : Profile
  "Road Safety Observation - Multiple Injuries?" : Profile
  "Road Safety Observation - Abrasion" : Profile
  "Road Safety Observation - Avulsion" : Profile
  "Road Safety Observation - Burn 1st Degree" : Profile
  "Road Safety Observation - Burn 2nd Degree" : Profile
  "Road Safety Observation - Burn 3rd Degree" : Profile
  "Road Safety Observation - Burn 4th Degree" : Profile
  "Road Safety Observation - Concussion" : Profile
  "Road Safety Observation - Contusion" : Profile
  "Road Safety Observation - Fracture (Closed)" : Profile
  "Road Safety Observation - Fracture (Open)" : Profile
  "Road Safety Observation - Open Wound" : Profile
  "Road Safety Observation - Traumatic Amputation" : Profile
  "Road Safety Observation - Other Specified Injury" : Profile
  "Road Safety Observation - Blood Alcohol Concentration" : Profile
  "Road Safety Observation - Condition of Patient" : Profile
  "Road Safety Observation - Outcome at Release" : Profile
  "Road Safety Observation - Outcome at Discharge" : Profile
  "Road Safety Observation - Status on Arrival" : Profile
  "Road Safety Observation - If Alive: Conscious/Unconscious" : Profile
  "Road Safety Observation - Vehicle Used" : Profile
  "Road Safety Observation - Clinical Remarks" : Profile
  "Road Safety Observation - Run Report Comments" : Profile
  "Road Safety Observation - Vehicle Condition" : Profile
  "Road Safety Observation - CCTV Available" : Profile
}

"RSAllergyIntolerance" --> "RSPatient" : patient
"RSClaim" --> "RSPatient" : patient
"RSCondition" --> "RSPatient" : subject
"RSCondition" --> "RSEncounter" : encounter
"RSDocumentReference" --> "RSPatient" : subject
"RSDocumentReference" --> "RSEncounter" : context.encounter
"RSEncounter" --> "RSOrganization" : serviceProvider
"RSEncounter" --> "RSOrganization" : hospitalization.origin
"RSEncounter" --> "PHCorePractitioner" : participant[receivedBy].individual
"RSEncounter" --> "PHCorePractitioner" : participant[teamLeader].individual
"RSEncounter" --> "PHCorePractitioner" : participant[treatmentOfficer].individual
"RSEncounter" --> "PHCorePractitioner" : participant[transportOfficer].individual
"RSEncounter" --> "PHCorePractitioner" : participant[assistant].individual
"RSMedicationStatement" --> "RSPatient" : subject
"RSObservation" --> "RSPatient" : subject
"RSObservation" --> "RSEncounter" : encounter
"RSHealthcareService" --> "RSOrganization" : providedBy
"RSHealthcareService" --> "RSLocation" : location
"RSProcedure" --> "RSPatient" : subject
"RSProcedure" --> "RSEncounter" : encounter
"RSProcedure" --> "PHCorePractitioner" : performer.actor
"RSServiceRequest" --> "RSHealthcareService" : supportingInfo
"RSServiceRequest" --> "RSOrganization" : supportingInfo
"RSServiceRequest" --> "PHCoreOrganization" : supportingInfo
"RSServiceRequest" --> "PHCorePractitioner" : supportingInfo
"RSServiceRequest" --> "PHCorePractitioner" : requester
"RSServiceRequest" --> "RSPatient" : subject
"RSServiceRequest" --> "RSEncounter" : encounter
"RSTask" --> "RSPatient" : for
"RSObservation" --> "Obs (RS profiles)" : profiles
"RSAllergyIntolerance" --|> "AllergyIntolerance"
"RSBundleEMS" --|> "Bundle"
"RSBundleONEISS" --|> "Bundle"
"RSClaim" --|> "Claim"
"RSCondition" --|> "Condition"
"RSDocumentReference" --|> "DocumentReference"
"RSEncounter" --|> "PHCoreEncounter"
"RSLocation" --|> "PHCoreLocation"
"RSMedicationStatement" --|> "MedicationStatement"
"RSObservation" --|> "PHCoreObservation"
"RSOrganization" --|> "PHCoreOrganization"
"RSHealthcareService" --|> "HealthcareService"
"RSPatient" --|> "PHCorePatient"
"RSProcedure" --|> "PHCoreProcedure"
"RSServiceRequest" --|> "ServiceRequest"
"RSTask" --|> "Task"

@enduml