@startuml
skinparam ClassFontName Arial
skinparam ClassFontSize 12
skinparam ClassAttributeIconSize 0
skinparam ClassBackgroundColor #EEF9EE
skinparam ClassBorderColor #6AA84F
skinparam ArrowColor #6A6A6A
skinparam ArrowThickness 1
hide empty methods
left to right direction

class "CauseOfRoadCrash" {
  value[x] : CodeableConcept
}
class "EDAvailability" {
  valueBoolean : — [1..1]
}
class "ExternalCauseDetailExt" {
  value[x] : string
}
class "FirstAidGiven" {
  value[x] : CodeableConcept
}
class "PartyAtFault" {
  value[x] : CodeableConcept
}
class "RSPatientAge" {
  value[x] : Age
}
class "PHCoreOccupation" {
  value[x] : CodeableConcept
}
class "ReportFormReceived" {
  value[x] : CodeableConcept
}
class "RoadNetworkShapeFile" {
  value[x] : url
}
class "SafetyNotesExt" {
  valueCodeableConcept : — [0..1]
  valueString : — [0..1]
}
class "SuppliesUsed" {
  valueCodeableConcept : — [0..1]
  valueReference : Reference(PHCoreMedication)
}
class "PHCoreMedication"
class "TrafficIncidentManagement" {
  value[x] : string
}
class "TranspoCoordination" {
  value[x] : CodeableConcept
}
class "TransportDetailsExt"
class "VehicleUsed" {
  valueCodeableConcept : — [1..1]
}
class "VehicleCondition" {
  value[x] : CodeableConcept
}
class "VehicleList" {
  value[x] : string
}
class "RSAllergyIntolerance" {
  patient : — [1..1]
  patient : Reference(RSPatient)
  code : — [1..1]
  clinicalStatus : — [1..1]
  verificationStatus : — [1..1]
}
class "RSPatient" {
  identifier : — [0..*]
  identifier[hospitalPatientID].type.coding : — [1..1]
  extension : — [0..1]
  address : — [0..1]
  address[permanent] : PHCoreAddress
  address[temporary] : PHCoreAddress
  managingOrganization : — [1..1]
  managingOrganization : Reference(PHCoreOrganization)
}
class "RSClaim" {
  total : — [1..1]
}
class "RSCondition" {
  clinicalStatus : — [1..1]
  verificationStatus : — [1..1]
  subject : — [1..1]
  subject : Reference(RSPatient)
  code.text : — [1..1]
  code.coding[icd10NatureOfInjury].system : — [1..1]
  code.coding[icd10ExternalCause].system : — [1..1]
}
class "RSDocumentReference" {
  status : — [1..1]
  type : — [0..1]
  category : — [0..*]
  subject : — [0..1]
  date : — [0..1]
  author : — [0..*]
  custodian : — [0..1]
  content : — [1..*]
  category : — [1..1]
  relatesTo : — [0..*]
  relatesTo.code : — [1..1]
  relatesTo.target : Reference(DocumentReference)
  content : — [0..1]
  content[roadNetworkFile].attachment : — [1..1]
  content[roadNetworkFile].attachment.contentType : — [1..1]
  content[roadNetworkFile].attachment.url : — [0..1]
  content[roadNetworkFile].attachment.data : — [0..1]
  content[roadNetworkFile].attachment.title : — [0..1]
  content[causeOfCrashFile].attachment : — [1..1]
  content[causeOfCrashFile].attachment.contentType : — [1..1]
  content[causeOfCrashFile].attachment.url : — [0..1]
  content[causeOfCrashFile].attachment.data : — [0..1]
  content[causeOfCrashFile].attachment.title : — [0..1]
  context.encounter : — [1..1]
  context.encounter : Reference(RSEncounter)
}
class "DocumentReference"
class "RSEncounter" {
  identifier : — [1..*]
  identifier[hospitalCaseNo].value : — [1..1]
  identifier[incidentNo].value : — [1..1]
  class : — [1..1]
  period : — [1..1]
  period.start : — [1..1]
  reasonCode : — [0..*]
  hospitalization.dischargeDisposition : — [0..1]
  hospitalization.destination : — [0..1]
  hospitalization.destination : Reference(PHCoreOrganization)
  serviceProvider : — [0..1]
  serviceProvider : Reference(PHCoreOrganization)
  participant[teamLeader].type : — [1..*]
  participant[teamLeader].individual : — [1..1]
  participant[teamLeader].individual : Reference(PHCorePractitioner)
  participant[treatmentOfficer].type : — [1..*]
  participant[treatmentOfficer].individual : — [1..1]
  participant[treatmentOfficer].individual : Reference(PHCorePractitioner)
  participant[transportOfficer].type : — [1..*]
  participant[transportOfficer].individual : — [1..1]
  participant[transportOfficer].individual : Reference(PHCorePractitioner)
  participant[assistant].type : — [1..*]
  participant[assistant].individual : — [1..1]
  participant[assistant].individual : Reference(PHCorePractitioner)
  participant[receivedBy].type : — [1..*]
  participant[receivedBy].individual : — [1..1]
  participant[receivedBy].individual : Reference(PHCorePractitioner)
  location : — [1..*]
  location : — [1..1]
  location : — [0..*]
  location[scene] : — [1..1]
  location[scene].location : Reference(PHCoreLocation)
  location[facility].location : — [1..1]
  location[facility].location : Reference(PHCoreLocation)
}
class "PHCoreOrganization"
class "PHCorePractitioner"
class "PHCoreLocation"
class "RSHealthcareService" {
  name : — [1..1]
  category : — [1..1]
  location : — [1..1]
  location : Reference(PHCoreLocation)
  active : — [1..1]
  extension : — [0..1]
}
class "RSMedicationStatement" {
  status : — [1..1]
  medicationCodeableConcept : — [1..1]
  medicationCodeableConcept.text : — [1..1]
  subject : — [1..1]
  subject : Reference(RSPatient)
  effective[x] : — [0..1]
  dateAsserted : — [0..1]
  dosage : — [0..*]
}
class "RSObservation" {
  status : — [1..1]
  category : — [0..*]
  code : — [1..1]
  subject : — [1..1]
  encounter : — [0..1]
  effective[x] : — [0..1]
  performer : — [0..*]
  component : — [0..*]
  component[DateTimeComponent].code : — [1..1]
  component[DateTimeComponent].value[x] : — [1..1]
  component : — [0..1]
  component[SystolicBP].valueQuantity : — [0..1]
  component[DiastolicBP].valueQuantity : — [0..1]
  component[HeartRate].valueQuantity : — [0..1]
  component[RespiratoryRate].valueQuantity : — [0..1]
  component[Temperature].valueQuantity : — [0..1]
  component[GCS_Eyes].valueInteger : — [0..1]
  component[GCS_Verbal].valueInteger : — [0..1]
  component[GCS_Motor].valueInteger : — [0..1]
  component[GCS_Total].valueInteger : — [0..1]
  bodySite : — [0..1]
  note : — [0..*]
  component[ExternalCause].valueCodeableConcept : — [0..1]
  component[CollisionType].code : — [1..1]
  component[PlaceOfOccurrence].code : — [1..1]
  component[ActivityAtIncident].code : — [1..1]
}
class "RSProcedure" {
  subject : Reference(RSPatient)
  performer : — [0..*]
  performer.actor : Reference(PHCorePractitioner)
  reasonCode : — [0..*]
  bodySite : — [0..*]
  outcome : — [0..1]
  note : — [0..*]
}
class "RSQuestionnaire" {
  status : — [1..1]
  name : — [1..1]
  title : — [1..1]
  item : — [1..1]
}
class "RSServiceRequest" {
  encounter : — [1..1]
  supportingInfo : — [0..1]
  supportingInfo[hospital] : Reference(PHCoreOrganization)
  supportingInfo[physician] : Reference(PHCorePractitioner)
  occurrenceDateTime : — [1..1]
}
class "RSTask" {
  status : — [1..1]
  executionPeriod : — [0..1]
  note : — [0..*]
  note.text : — [1..1]
}

"SuppliesUsed" --> "PHCoreMedication" : valueReference
"RSAllergyIntolerance" --> "RSPatient" : patient
"RSCondition" --> "RSPatient" : subject
"RSDocumentReference" --> "DocumentReference" : relatesTo.target
"RSDocumentReference" --> "RSEncounter" : context.encounter
"RSEncounter" --> "PHCoreOrganization" : hospitalization.destination
"RSEncounter" --> "PHCoreOrganization" : serviceProvider
"RSEncounter" --> "PHCorePractitioner" : participant[teamLeader].individual
"RSEncounter" --> "PHCorePractitioner" : participant[treatmentOfficer].individual
"RSEncounter" --> "PHCorePractitioner" : participant[transportOfficer].individual
"RSEncounter" --> "PHCorePractitioner" : participant[assistant].individual
"RSEncounter" --> "PHCorePractitioner" : participant[receivedBy].individual
"RSEncounter" --> "PHCoreLocation" : location[scene].location
"RSEncounter" --> "PHCoreLocation" : location[facility].location
"RSHealthcareService" --> "PHCoreLocation" : location
"RSMedicationStatement" --> "RSPatient" : subject
"RSPatient" --> "PHCoreOrganization" : managingOrganization
"RSProcedure" --> "RSPatient" : subject
"RSProcedure" --> "PHCorePractitioner" : performer.actor
"RSServiceRequest" --> "PHCoreOrganization" : supportingInfo[hospital]
"RSServiceRequest" --> "PHCorePractitioner" : supportingInfo[physician]

@enduml