@startuml
skinparam ClassFontName Arial
skinparam ClassFontSize 12
skinparam ClassAttributeIconSize 0
skinparam ClassBackgroundColor #EEF9EE
skinparam ClassBorderColor #6AA84F
skinparam ArrowColor #6A6A6A
skinparam ArrowThickness 1
hide empty methods
top to bottom direction

class "RSAllergyIntolerance" {
  code : — [0..1]
  patient : — [1..1]
  patient : Reference(RSPatient)
  encounter : Reference(RSEncounter)
}
class "AllergyIntolerance"
class "RSPatient" {
  identifier : — [0..*]
  name : — [1..*]
  name.family : — [0..1]
  name.given : — [1..*]
  name.given : — [1..2]
  name.given : — [0..1]
  birthDate : — [0..1]
  telecom : — [0..*]
  address : — [0..*]
  address.line : — [0..*]
  address.extension : — [0..*]
}
class "RSEncounter" {
  status : — [1..1]
  class : — [1..1]
  identifier : — [1..*]
  subject : — [1..1]
  subject : Reference(RSPatient)
  period.start : — [1..1]
  serviceProvider : — [0..1]
  serviceProvider : Reference(RSOrganization)
  participant : — [0..*]
  hospitalization.dischargeDisposition : — [0..1]
  hospitalization.destination : — [0..1]
  location : — [0..1]
  location[accidentSite].location : — [1..1]
  location[accidentSite].location : Reference(RSIncidentLocation)
  location[facility].location : — [1..1]
  location[facility].location : Reference(RSServiceLocation)
  location[facility].location.type : — [0..1]
  identifier : — [0..1]
  identifier[incidentNumber].type : — [1..1]
  identifier[incidentNumber].type.coding : — [1..1]
  identifier[hospitalCaseNo].type : — [1..1]
  identifier[hospitalCaseNo].type.coding : — [1..1]
  hospitalization.origin : — [0..1]
  hospitalization.origin : Reference(RSOrganization)
  participant : — [0..1]
  participant[receivedBy].individual : — [0..1]
  participant[receivedBy].individual : Reference(PHCorePractitioner)
  participant[teamLeader].individual : — [0..1]
  participant[teamLeader].individual : Reference(PHCorePractitioner)
  participant[treatmentOfficer].individual : — [0..1]
  participant[treatmentOfficer].individual : Reference(PHCorePractitioner)
  participant[transportOfficer].individual : — [0..1]
  participant[transportOfficer].individual : Reference(PHCorePractitioner)
  participant[assistant].individual : — [0..1]
  participant[assistant].individual : Reference(PHCorePractitioner)
}
class "RSCompositionEMS" {
  status : — [1..1]
  subject : — [1..1]
  subject : Reference(RSPatient)
  date : — [1..1]
  author : — [1..1]
  section : — [1..*]
  section[workflow].entry : — [1..*]
  section[workflow].entry : Reference
  section[incident].entry : — [0..*]
  section[incident].entry : Reference
  section[vitals].entry : — [0..*]
  section[vitals].entry : Reference
  section[clinical].entry : — [0..*]
  section[clinical].entry : Reference(RSObsClinicalRemarks | RSProcedure | RSCondition)
  section[documents].entry : — [0..*]
  section[documents].entry : Reference(RSDocumentReference)
  section[procedures].entry : — [0..*]
  section[procedures].entry : Reference(RSProcedure | RSServiceRequest | RSTask)
}
class "Composition"
class "RSProcedure" {
  status : — [1..1]
  code : — [0..1]
  subject : — [1..1]
  subject : Reference(RSPatient)
  encounter : — [0..1]
  encounter : Reference(RSEncounter)
  performer : — [0..*]
  performer.actor : Reference(PHCorePractitioner)
  note : — [0..*]
}
class "RSCondition" {
  subject : — [1..1]
  subject : Reference(RSPatient)
  encounter : — [0..1]
  encounter : Reference(RSEncounter)
  category : — [0..1]
  severity : — [0..1]
  code : — [0..1]
  code.text : — [0..1]
  onset[x] : — [0..1]
  note : — [0..*]
}
class "RSDocumentReference" {
  status : — [1..1]
  type : — [0..1]
  subject : — [0..1]
  subject : Reference(RSPatient)
  context.encounter : — [0..1]
  context.encounter : Reference(RSEncounter)
  content : — [1..*]
  content.attachment.url : — [1..1]
  content.format : — [0..1]
}
class "RSServiceRequest" {
  status : — [1..1]
  occurrenceDateTime : — [0..1]
  supportingInfo : — [0..*]
  supportingInfo : Reference(RSOrganization | PHCorePractitioner)
  requester : — [0..1]
  requester : Reference(PHCorePractitioner)
  code : — [1..1]
  code.coding : — [1..1]
  subject : — [1..1]
  subject : Reference(RSPatient)
  encounter : — [0..1]
  encounter : Reference(RSEncounter)
}
class "RSTask" {
  status : — [1..1]
  executionPeriod : — [0..1]
  note : — [0..*]
  for : — [0..1]
  for : Reference(RSPatient)
  focus : — [0..1]
  input : — [0..*]
  output : — [0..*]
}
class "RSBundleEMS" {
  type : — [1..1]
  entry : — [1..*]
  entry.resource : — [1..1]
  entry[composition].resource : RSCompositionEMS
  entry[patient].resource : RSPatient
  entry[encounter].resource : RSEncounter
  entry[location].resource : RSIncidentLocation
  entry[observationDateReceived].resource : RSObsDateReceived
  entry[observationTimeEnroute].resource : RSObsTimeEnroute
  entry[observationTimeOnScene].resource : RSObsTimeOnScene
  entry[observationTimeDeparted].resource : RSObsTimeDepartedScene
  entry[observationTimeHospitalArrival].resource : RSObsTimeHospitalArrival
  entry[observationTimeStationArrival].resource : RSObsTimeStationArrival
  entry[observationVitals].resource : RSObsRespiratoryRate
  entry[observationGCS].resource : RSObsGCS
  entry[observationReportedComplaint].resource : RSObsReportedComplaint
  entry[observationCallSource].resource : RSObsCallSource
  entry[observationVehicleUsed].resource : RSObsVehicleUsed
  entry[observationRunReportComments].resource : RSObsRunReportComments
  entry[observationClinicalRemarks].resource : RSObsClinicalRemarks
  entry[document].resource : RSDocumentReference
  entry[task].resource : RSTask
  entry[serviceRequest].resource : RSServiceRequest
  entry[procedure].resource : RSProcedure
  entry[claim].resource : RSClaim
}
class "Bundle"
class "RSCompositionONEISS" {
  status : — [1..1]
  subject : — [1..1]
  subject : Reference(RSPatient)
  date : — [1..1]
  author : — [1..1]
  section : — [1..*]
  section[patient].entry : — [1..1]
  section[patient].entry : Reference(RSPatient)
  section[encounter].entry : — [1..1]
  section[encounter].entry : Reference(RSEncounter)
  section[clinical].entry : — [0..*]
  section[clinical].entry : Reference
  section[injuries].entry : — [0..*]
  section[injuries].entry : Reference
  section[incident].entry : — [0..*]
  section[incident].entry : Reference
  section[documents].entry : — [0..*]
  section[documents].entry : Reference(RSDocumentReference)
}
class "RSBundleONEISS" {
  type : — [1..1]
  entry : — [1..*]
  entry.resource : — [1..1]
  entry[composition].resource : RSCompositionONEISS
  entry[patient].resource : RSPatient
  entry[encounter].resource : RSEncounter
  entry[conditionInitial].resource : RSConditionInitialImpression
  entry[conditionFinal].resource : RSConditionFinalDiagnosis
  entry[observationClinical].resource : RSObsOtherRiskFactors
  entry[observationIncident].resource : RSObsInjuryDateTime
  entry[observationExternalCause].resource : RSObsECBitesStings
  entry[observationInjuries].resource : RSObsMultipleInjuries
  entry[observationExtentOfInjury].resource : RSObsExtentOfInjury
  entry[observationTransferredFromFacility].resource : RSObsTransferredFromFacility
  entry[observationReferredByFacility].resource : RSObsReferredByFacility
  entry[document].resource : RSDocumentReference
  entry[serviceRequest].resource : RSServiceRequest
  entry[procedure].resource : RSProcedure
}
class "RSCompositionPostCrash" {
  status : — [1..1]
  subject : — [1..1]
  subject : Reference(RSPatient)
  date : — [1..1]
  author : — [1..*]
  section : — [1..*]
  section[patient].entry : — [1..1]
  section[patient].entry : Reference(RSPatient)
  section[incident].entry : — [0..*]
  section[incident].entry : Reference
  section[documents].entry : — [0..*]
  section[documents].entry : Reference(RSDocumentReference)
}
class "RSBundlePostCrash" {
  type : — [1..1]
  entry : — [1..*]
  entry.resource : — [1..1]
  entry[composition].resource : RSCompositionPostCrash
  entry[patient].resource : RSPatient
  entry[encounter].resource : RSEncounter
  entry[observationPostCrash].resource : RSObsCollisionType
  entry[document].resource : RSDocumentReference
}
class "RSClaim" {
  patient : — [1..1]
  patient : Reference(RSPatient)
  total : — [0..1]
}
class "Claim"
class "Condition"
class "RSConditionProblem" {
  code : — [0..1]
  category.coding : — [1..1]
}
class "RSConditionInitialImpression" {
  code : — [0..1]
  category.coding : — [1..1]
}
class "RSConditionFinalDiagnosis" {
  code : — [0..1]
}
class "RSConditionNatureOfInjury" {
  category : — [0..1]
  category.coding.system : — [0..1]
  category.coding.display : — [0..1]
  code : — [0..1]
}
class "RSConditionExternalCause" {
  category : — [0..1]
  category.coding.system : — [0..1]
  category.coding.display : — [0..1]
  code : — [0..1]
}
class "DocumentReference"
class "PHCoreEncounter"
class "RSOrganization" {
  active : — [0..1]
  type : — [0..*]
  name : — [1..1]
  identifier : — [0..*]
  telecom : — [0..*]
  address : — [0..*]
}
class "RSIncidentLocation" {
  name : — [0..1]
  address : — [0..1]
  address.line : — [0..*]
  address.extension : — [0..*]
  position : — [0..1]
  position.longitude : — [1..1]
  position.latitude : — [1..1]
}
class "RSServiceLocation" {
  name : — [0..1]
  address : — [0..1]
  type : — [0..1]
}
class "PHCorePractitioner"
class "PHCoreLocation"
class "RSMedicationStatement" {
  subject : — [1..1]
  subject : Reference(RSPatient)
  effective[x] : — [0..1]
  medicationCodeableConcept : — [1..1]
  medicationCodeableConcept.text : — [1..1]
}
class "MedicationStatement"
class "RSObservation" {
  status : — [1..1]
  subject : — [1..1]
  subject : Reference(RSPatient)
  code : — [1..1]
  encounter : — [0..1]
  encounter : Reference(RSEncounter)
  effective[x] : — [0..1]
  performer : — [0..*]
  value[x] : — [0..1]
  note : — [0..*]
}
class "PHCoreObservation"
class "PHCoreOrganization"
class "RSHealthcareService" {
  active : — [0..1]
  type : — [0..*]
  name : — [0..1]
  identifier : — [0..*]
  telecom : — [0..*]
  providedBy : — [1..1]
  providedBy : Reference(RSOrganization)
  location : — [0..*]
  location : Reference(RSIncidentLocation)
  coverageArea : — [0..*]
}
class "HealthcareService"
class "PHCorePatient"
class "PHCoreProcedure"
class "RSProcedureTransportCoordination" {
  code : — [1..1]
  code.coding : — [1..1]
}
class "ServiceRequest"
class "Task"
class "Obs (RS profiles)" {
  "RS Observation - Respiratory Rate" : Profile
  "RS Observation - Pulse Rate" : Profile
  "RS Observation - Blood Pressure" : Profile
  "RS Observation - Body Temperature" : Profile
  "RS Observation - Level of Consciousness (AVPU)" : Profile
  "RS Observation - Pupils" : Profile
  "RS Observation - Cyanosis" : Profile
  "RS Observation - Glasgow Coma Scale" : Profile
  "RS Observation - Respiratory Rhythm" : Profile
  "RS Observation - Breath Sounds" : Profile
  "RS Observation - Pulse Rhythm" : Profile
  "RS Observation - Pulse Quality" : Profile
  "RS Observation - Date/Time Received by EMS" : Profile
  "RS Observation - Time Received" : Profile
  "RS Observation - Time Enroute" : Profile
  "RS Observation - Time On Scene" : Profile
  "RS Observation - Time Departed Scene" : Profile
  "RS Observation - Time of Hospital Arrival" : Profile
  "RS Observation - Time of Emergency Station Arrival" : Profile
  "RS Observation - Date/Time of Injury" : Profile
  "RS Observation - Date of Injury" : Profile
  "RS Observation - Time of Injury" : Profile
  "RS Observation - Injury Intent" : Profile
  "RS Observation - Transport/Vehicular Accident" : Profile
  "RS Observation - Mode of Transport to Facility" : Profile
  "RS Observation - Date of Consultation" : Profile
  "RS Observation - Time of Consultation" : Profile
  "RS Observation - Triage Priority" : Profile
  "RS Observation - Priority Level (Urgency)" : Profile
  "RS Observation - Place of Occurrence" : Profile
  "RS Observation - Activity at Time of Incident" : Profile
  "RS Observation - Collision vs Non-Collision" : Profile
  "RS Observation - Patient's Vehicle" : Profile
  "RS Observation - Other Vehicle/Object Involved" : Profile
  "RS Observation - Position of Patient" : Profile
  "RS Observation - How Many Vehicles Involved" : Profile
  "RS Observation - How Many Patients Involved" : Profile
  "RS Observation - Collision Type" : Profile
  "RS Observation - Presence of Traffic Investigator" : Profile
  "RS Observation - Other Risk Factors" : Profile
  "RS Observation - Safety Accessories" : Profile
  "RS Observation - Reported Complaint" : Profile
  "RS Observation - Call Source" : Profile
  "RS Observation - External Cause: Bites/Stings" : Profile
  "RS Observation - External Cause: Burns" : Profile
  "RS Observation - External Cause: Burns" : Profile
  "RS Observation - External Cause: Chemical/Substance" : Profile
  "RS Observation - External Cause: Contact with Sharp Object" : Profile
  "RS Observation - External Cause: Drowning" : Profile
  "RS Observation - External Cause: Exposure to Forces of Nature" : Profile
  "RS Observation - External Cause: Fall" : Profile
  "RS Observation - External Cause: Firecracker" : Profile
  "RS Observation - External Cause: Gunshot" : Profile
  "RS Observation - External Cause: Hanging/Strangulation" : Profile
  "RS Observation - External Cause: Mauling/Assault" : Profile
  "RS Observation - External Cause: Sexual Assault/Abuse/Rape (Alleged)" : Profile
  "RS Observation - External Cause: Other" : Profile
  "RS Observation - Extent of Injury" : Profile
  "RS Observation - Transferred From Facility" : Profile
  "RS Observation - Referred By Facility" : Profile
  "RS Observation - Multiple Injuries?" : Profile
  "RS Observation - Abrasion" : Profile
  "RS Observation - Avulsion" : Profile
  "RS Observation - Concussion" : Profile
  "RS Observation - Contusion" : Profile
  "RS Observation - Fracture" : Profile
  "RS Observation - Open Wound" : Profile
  "RS Observation - Traumatic Amputation" : Profile
  "RS Observation - Other Specified Injury" : Profile
  "RS Observation - Blood Alcohol Concentration" : Profile
  "RS Observation - Condition of Patient" : Profile
  "RS Observation - Outcome at Release" : Profile
  "RS Observation - Outcome at Discharge" : Profile
  "RS Observation - Status on Arrival" : Profile
  "RS Observation - If Alive: Conscious/Unconscious" : Profile
  "RS Observation - Vehicle Used" : Profile
  "RS Observation - Clinical Remarks" : Profile
  "RS Observation - Run Report Comments" : Profile
  "RS Observation - CCTV Available" : Profile
}

"RSAllergyIntolerance" --> "RSPatient" : patient
"RSAllergyIntolerance" --> "RSEncounter" : encounter
"RSCompositionEMS" --> "RSPatient" : subject
"RSCompositionEMS" --> "RSProcedure" : section[clinical].entry
"RSCompositionEMS" --> "RSCondition" : section[clinical].entry
"RSCompositionEMS" --> "RSDocumentReference" : section[documents].entry
"RSCompositionEMS" --> "RSProcedure" : section[procedures].entry
"RSCompositionEMS" --> "RSServiceRequest" : section[procedures].entry
"RSCompositionEMS" --> "RSTask" : section[procedures].entry
"RSCompositionONEISS" --> "RSPatient" : subject
"RSCompositionONEISS" --> "RSPatient" : section[patient].entry
"RSCompositionONEISS" --> "RSEncounter" : section[encounter].entry
"RSCompositionONEISS" --> "RSDocumentReference" : section[documents].entry
"RSCompositionPostCrash" --> "RSPatient" : subject
"RSCompositionPostCrash" --> "RSPatient" : section[patient].entry
"RSCompositionPostCrash" --> "RSDocumentReference" : section[documents].entry
"RSClaim" --> "RSPatient" : patient
"RSCondition" --> "RSPatient" : subject
"RSCondition" --> "RSEncounter" : encounter
"RSDocumentReference" --> "RSPatient" : subject
"RSDocumentReference" --> "RSEncounter" : context.encounter
"RSEncounter" --> "RSPatient" : subject
"RSEncounter" --> "RSOrganization" : serviceProvider
"RSEncounter" --> "RSIncidentLocation" : location[accidentSite].location
"RSEncounter" --> "RSServiceLocation" : location[facility].location
"RSEncounter" --> "RSOrganization" : hospitalization.origin
"RSEncounter" --> "PHCorePractitioner" : participant[receivedBy].individual
"RSEncounter" --> "PHCorePractitioner" : participant[teamLeader].individual
"RSEncounter" --> "PHCorePractitioner" : participant[treatmentOfficer].individual
"RSEncounter" --> "PHCorePractitioner" : participant[transportOfficer].individual
"RSEncounter" --> "PHCorePractitioner" : participant[assistant].individual
"RSMedicationStatement" --> "RSPatient" : subject
"RSObservation" --> "RSPatient" : subject
"RSObservation" --> "RSEncounter" : encounter
"RSHealthcareService" --> "RSOrganization" : providedBy
"RSHealthcareService" --> "RSIncidentLocation" : location
"RSProcedure" --> "RSPatient" : subject
"RSProcedure" --> "RSEncounter" : encounter
"RSProcedure" --> "PHCorePractitioner" : performer.actor
"RSServiceRequest" --> "RSOrganization" : supportingInfo
"RSServiceRequest" --> "PHCorePractitioner" : supportingInfo
"RSServiceRequest" --> "PHCorePractitioner" : requester
"RSServiceRequest" --> "RSPatient" : subject
"RSServiceRequest" --> "RSEncounter" : encounter
"RSTask" --> "RSPatient" : for
"RSObservation" --> "Obs (RS profiles)" : profiles
"RSAllergyIntolerance" --|> "AllergyIntolerance"
"RSCompositionEMS" --|> "Composition"
"RSBundleEMS" --|> "Bundle"
"RSCompositionONEISS" --|> "Composition"
"RSBundleONEISS" --|> "Bundle"
"RSCompositionPostCrash" --|> "Composition"
"RSBundlePostCrash" --|> "Bundle"
"RSClaim" --|> "Claim"
"RSCondition" --|> "Condition"
"RSConditionProblem" --|> "RSCondition"
"RSConditionInitialImpression" --|> "RSCondition"
"RSConditionFinalDiagnosis" --|> "RSCondition"
"RSConditionNatureOfInjury" --|> "RSCondition"
"RSConditionExternalCause" --|> "RSCondition"
"RSDocumentReference" --|> "DocumentReference"
"RSEncounter" --|> "PHCoreEncounter"
"RSIncidentLocation" --|> "PHCoreLocation"
"RSServiceLocation" --|> "PHCoreLocation"
"RSMedicationStatement" --|> "MedicationStatement"
"RSObservation" --|> "PHCoreObservation"
"RSOrganization" --|> "PHCoreOrganization"
"RSHealthcareService" --|> "HealthcareService"
"RSPatient" --|> "PHCorePatient"
"RSProcedure" --|> "PHCoreProcedure"
"RSProcedureTransportCoordination" --|> "RSProcedure"
"RSServiceRequest" --|> "ServiceRequest"
"RSTask" --|> "Task"

@enduml