ValueSet: SILPH___Element_Terminology__VS_
Id: SILPH-ElementTerminologyVS
Title: "SILPH - Element Terminology (VS)"
Description: "SILPH Value Set for Element Terminology"
* ^meta.versionId = "4"
* ^meta.lastUpdated = "2025-10-30T00:34:00.984+00:00"
* ^url = "http://www.roadsafetyph.doh.gov.ph/ValueSet/SILPH-ElementTerminology"
* ^version = "0.1.0"
* ^status = #draft
* ^contact.telecom.system = #email
* ^expansion.identifier = "urn:uuid:81c2a382-b060-45c2-a691-1753f17a10e4"
* ^expansion.timestamp = "2025-10-29T23:49:35+00:00"
* ^expansion.total = 45
* ^expansion.parameter[0].name = "used-codesystem"
* ^expansion.parameter[=].valueUri = "http://www.roadsafetyph.doh.gov.ph/CodeSystem|0.2.0"
* ^expansion.parameter[+].name = "version"
* ^expansion.parameter[=].valueUri = "http://www.roadsafetyph.doh.gov.ph/CodeSystem|0.2.0"
* ^expansion.parameter[+].name = "used-codesystem"
* ^expansion.parameter[=].valueUri = "http://snomed.info/sct|http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.parameter[+].name = "version"
* ^expansion.parameter[=].valueUri = "http://snomed.info/sct|http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.parameter[+].name = "used-codesystem"
* ^expansion.parameter[=].valueUri = "http://loinc.org|2.78"
* ^expansion.parameter[+].name = "version"
* ^expansion.parameter[=].valueUri = "http://loinc.org|2.78"
* ^expansion.parameter[+].name = "warning-draft"
* ^expansion.parameter[=].valueUri = "http://www.roadsafetyph.doh.gov.ph/CodeSystem|0.2.0"
* ^expansion.parameter[+].name = "warning-draft"
* ^expansion.parameter[=].valueUri = "http://www.roadsafetyph.doh.gov.ph/ValueSet/SILPH-ElementTerminology|0.1.0"
* ^expansion.contains[0].system = "http://www.roadsafetyph.doh.gov.ph/CodeSystem"
* ^expansion.contains[=].version = "0.2.0"
* ^expansion.contains[=].code = #INJURYFRONT
* ^expansion.contains[=].display = "Site of Injury/Pain - Front Part of Body"
* ^expansion.contains[+].system = "http://www.roadsafetyph.doh.gov.ph/CodeSystem"
* ^expansion.contains[=].version = "0.2.0"
* ^expansion.contains[=].code = #INJURYBACK
* ^expansion.contains[=].display = "Site of Injury/Pain - Back Part of Body"
* ^expansion.contains[+].system = "http://www.roadsafetyph.doh.gov.ph/CodeSystem"
* ^expansion.contains[=].version = "0.2.0"
* ^expansion.contains[=].code = #RRFREMARKS
* ^expansion.contains[=].display = "Run Report Form Remarks"
* ^expansion.contains[+].system = "http://www.roadsafetyph.doh.gov.ph/CodeSystem"
* ^expansion.contains[=].version = "0.2.0"
* ^expansion.contains[=].code = #MVA-COLLISION
* ^expansion.contains[=].display = "FOR TRANSPORT/VEHICULAR ACCIDENT ONLY (Collision; Non-Collision)"
* ^expansion.contains[+].system = "http://www.roadsafetyph.doh.gov.ph/CodeSystem"
* ^expansion.contains[=].version = "0.2.0"
* ^expansion.contains[=].code = #PATIENTVEHICLE
* ^expansion.contains[=].display = "Vehicles Involved: Patient's Vehicle"
* ^expansion.contains[+].system = "http://www.roadsafetyph.doh.gov.ph/CodeSystem"
* ^expansion.contains[=].version = "0.2.0"
* ^expansion.contains[=].code = #OTHERVEHICLE
* ^expansion.contains[=].display = "Other Vehicle/Object Involved (for COLLISION accident ONLY)"
* ^expansion.contains[+].system = "http://www.roadsafetyph.doh.gov.ph/CodeSystem"
* ^expansion.contains[=].version = "0.2.0"
* ^expansion.contains[=].code = #PATIENTPOSITION
* ^expansion.contains[=].display = "Position of Patient"
* ^expansion.contains[+].system = "http://www.roadsafetyph.doh.gov.ph/CodeSystem"
* ^expansion.contains[=].version = "0.2.0"
* ^expansion.contains[=].code = #PLACEOCCURRENCE
* ^expansion.contains[=].display = "Place of Occurrence"
* ^expansion.contains[+].system = "http://www.roadsafetyph.doh.gov.ph/CodeSystem"
* ^expansion.contains[=].version = "0.2.0"
* ^expansion.contains[=].code = #COLLISIONTYPE
* ^expansion.contains[=].display = "Collision Type"
* ^expansion.contains[+].system = "http://www.roadsafetyph.doh.gov.ph/CodeSystem"
* ^expansion.contains[=].version = "0.2.0"
* ^expansion.contains[=].code = #COORDINATIONDONE
* ^expansion.contains[=].display = "Was Transport Coordinated with Receiving Hospital?"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #609328004
* ^expansion.contains[=].display = "Allergic disposition (finding)"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #386725007
* ^expansion.contains[=].display = "Body temperature (observable entity)"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #6942003
* ^expansion.contains[=].display = "Level of consciousness (observable entity)"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #3415004
* ^expansion.contains[=].display = "Cyanosis (finding)"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #55607006
* ^expansion.contains[=].display = "Problem (finding)"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #116154003
* ^expansion.contains[=].display = "Patient (person)"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #399963005
* ^expansion.contains[=].display = "Abrasion (disorder)"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #125666000
* ^expansion.contains[=].display = "Burn (disorder)"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #46541008
* ^expansion.contains[=].display = "Second degree burn injury (morphologic abnormality)"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #110030002
* ^expansion.contains[=].display = "Concussion injury of brain (disorder)"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #125667009
* ^expansion.contains[=].display = "Contusion (disorder)"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #125605004
* ^expansion.contains[=].display = "Fracture of bone (disorder)"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #423125000
* ^expansion.contains[=].display = "Closed fracture of bone (disorder)"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #125643001
* ^expansion.contains[=].display = "Open wound (disorder)"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #417163006
* ^expansion.contains[=].display = "Traumatic or non-traumatic injury (disorder)"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #242651001
* ^expansion.contains[=].display = "Injury caused by animal (disorder)"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #1912002
* ^expansion.contains[=].display = "Fall (event)"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #63409001
* ^expansion.contains[=].display = "Struck by firearm discharge (event)"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #52684005
* ^expansion.contains[=].display = "Assault (event)"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #248110007
* ^expansion.contains[=].display = "Sexual assault (event)"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #773760007
* ^expansion.contains[=].display = "Traumatic event (event)"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #260870009
* ^expansion.contains[=].display = "Priority (attribute)"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #364703007
* ^expansion.contains[=].display = "Employment detail (observable entity)"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #218247007
* ^expansion.contains[=].display = "Late effect of motor vehicle accident (disorder)"
* ^expansion.contains[+].system = "http://loinc.org"
* ^expansion.contains[=].version = "2.78"
* ^expansion.contains[=].code = #30976-5
* ^expansion.contains[=].display = "Date received Form"
* ^expansion.contains[+].system = "http://loinc.org"
* ^expansion.contains[=].version = "2.78"
* ^expansion.contains[=].code = #69472-9
* ^expansion.contains[=].display = "Unit responded [Date and time] Vehicle"
* ^expansion.contains[+].system = "http://loinc.org"
* ^expansion.contains[=].version = "2.78"
* ^expansion.contains[=].code = #69475-2
* ^expansion.contains[=].display = "Responding unit left the scene with a patient [Date and time] Vehicle"
* ^expansion.contains[+].system = "http://loinc.org"
* ^expansion.contains[=].version = "2.78"
* ^expansion.contains[=].code = #11288-8
* ^expansion.contains[=].display = "Arrival time documented"
* ^expansion.contains[+].system = "http://loinc.org"
* ^expansion.contains[=].version = "2.78"
* ^expansion.contains[=].code = #90123-1
* ^expansion.contains[=].display = "Response team leader name"
* ^expansion.contains[+].system = "http://loinc.org"
* ^expansion.contains[=].version = "2.78"
* ^expansion.contains[=].code = #11375-3
* ^expansion.contains[=].display = "Injury intent"
* ^expansion.contains[+].system = "http://loinc.org"
* ^expansion.contains[=].version = "2.78"
* ^expansion.contains[=].code = #95376-0
* ^expansion.contains[=].display = "Type of animal exposed to"
* ^expansion.contains[+].system = "http://loinc.org"
* ^expansion.contains[=].version = "2.78"
* ^expansion.contains[=].code = #11372-0
* ^expansion.contains[=].display = "Injury associated activity"
* ^expansion.contains[+].system = "http://loinc.org"
* ^expansion.contains[=].version = "2.78"
* ^expansion.contains[=].code = #74199-1
* ^expansion.contains[=].display = "Transferred from another acute care facility [NTDS]"
* ^expansion.contains[+].system = "http://loinc.org"
* ^expansion.contains[=].version = "2.78"
* ^expansion.contains[=].code = #74286-6
* ^expansion.contains[=].display = "Transport mode to hospital [NTDS]"
* ^expansion.contains[+].system = "http://loinc.org"
* ^expansion.contains[=].version = "2.78"
* ^expansion.contains[=].code = #77999-1
* ^expansion.contains[=].display = "Case notification comment"
* SILPH_Road_Safety_Local_Codes#INJURYFRONT "Site of Injury/Pain - Front Part of Body"
* SILPH_Road_Safety_Local_Codes#INJURYBACK "Site of Injury/Pain - Back Part of Body"
* SILPH_Road_Safety_Local_Codes#RRFREMARKS "Run Report Form Remarks"
* SILPH_Road_Safety_Local_Codes#MVA-COLLISION "FOR TRANSPORT/VEHICULAR ACCIDENT ONLY (Collision; Non-Collision)"
* SILPH_Road_Safety_Local_Codes#PATIENTVEHICLE "Vehicles Involved: Patient's Vehicle"
* SILPH_Road_Safety_Local_Codes#OTHERVEHICLE "Other Vehicle/Object Involved (for COLLISION accident ONLY)"
* SILPH_Road_Safety_Local_Codes#PATIENTPOSITION "Position of Patient"
* SILPH_Road_Safety_Local_Codes#PLACEOCCURRENCE "Place of Occurrence"
* SILPH_Road_Safety_Local_Codes#ER_OUTPATIENT_OUTCOME "ER/Outpatient Outcome"
* SILPH_Road_Safety_Local_Codes#INPATIENT_OUTCOME "Inpatient Outcome"
* SILPH_Road_Safety_Local_Codes#COLLISIONTYPE "Collision Type"
* SILPH_Road_Safety_Local_Codes#COORDINATIONDONE "Was Transport Coordinated with Receiving Hospital?"
* $SCT#405796007 "Time of call for help (observable entity)"
* $SCT#405798008 "Time of arrival of emergency services (observable entity)"
* $SCT#405799000 "Time of arrival at hospital (observable entity)"
* $SCT#1269489004 "Chief complaint (observable entity)"
* $SCT#398099009 "Street address (observable entity)"
* $SCT#397663001 "Referral source (finding)"
* $SCT#184096005 "Patient surname (observable entity)"
* $SCT#184095009 "Patient forename (observable entity)"
* $SCT#405622006 "Patient middle name (observable entity)"
* $SCT#397669002 "Age (qualifier value)"
* $SCT#184100006 "Patient sex (observable entity)"
* $SCT#734005006 "Telephone number (property) (qualifier value)"
* $SCT#417662000 "History of clinical finding in subject (situation)"
* $SCT#513881000000106 "Current medication as reported by patient (observable entity)"
* $SCT#609328004 "Allergic disposition (finding)"
* $SCT#86290005 "Respiratory rate (observable entity)"
* $SCT#248582003 "Rhythm of respiration (observable entity)"
* $SCT#52653008 "Respiratory sounds (observable entity)"
* $SCT#78564009 "Heart rate measured at systemic artery (observable entity)"
* $SCT#364095004 "Pulse rhythm (observable entity)"
* $SCT#366201008 "Finding of pulse volume (finding)"
* $SCT#271649006 "Systolic blood pressure (observable entity)"
* $SCT#271650006 "Diastolic blood pressure (observable entity)"
* $SCT#386725007 "Body temperature (observable entity)"
* $SCT#6942003 "Level of consciousness (observable entity)"
* $SCT#271733001 "Pupil reaction (observable entity)"
* $SCT#3415004 "Cyanosis (finding)"
* $SCT#281395000 "Glasgow Coma Score eye opening subscore (observable entity)"
* $SCT#281397008 "Glasgow Coma Scale verbal response subscore (observable entity)"
* $SCT#281396004 "Glasgow Coma Scale motor response subscore (observable entity)"
* $SCT#248241002 "Glasgow coma score (observable entity)"
* $SCT#55607006 "Problem (finding)"
* $SCT#119270007 "Management procedure (procedure)"
* $SCT#397897005 "Paramedic (occupation)"
* $SCT#159738005 "Ambulanceman (occupation)"
* $SCT#22515006 "Medical Assistant (occupation)"
* $SCT#36030000 "Transport vehicle, device (physical object)"
* $SCT#184107009 "Patient hospital number (observable entity)"
* $SCT#722248002 "Patient hospital visit number (observable entity)"
* $SCT#116154003 "Patient (person)"
* $SCT#184099003 "Date of birth (observable entity)"
* $SCT#439771001 "Date of event (observable entity)"
* $SCT#263501003 "Time of onset (observable entity)"
* $SCT#406543005 "Date of visit (observable entity)"
* $SCT#406544004 "Time of visit (observable entity)"
* $SCT#386308007 "First aid (procedure)"
* $SCT#262519004 "Multiple injuries (disorder)"
* $SCT#399963005 "Abrasion (disorder)"
* $SCT#284554003 "Avulsion - injury (disorder)"
* $SCT#125666000 "Burn (disorder)"
* $SCT#77140003 "First degree burn injury (morphologic abnormality)"
* $SCT#46541008 "Second degree burn injury (morphologic abnormality)"
* $SCT#80247002 "Third degree burn injury (morphologic abnormality)"
* $SCT#770400008 "Fourth degree burn injury (morphologic abnormality)"
* $SCT#110030002 "Concussion injury of brain (disorder)"
* $SCT#125667009 "Contusion (disorder)"
* $SCT#125605004 "Fracture of bone (disorder)"
* $SCT#423125000 "Closed fracture of bone (disorder)"
* $SCT#397181002 "Open fracture (disorder)"
* $SCT#125643001 "Open wound (disorder)"
* $SCT#262595009 "Traumatic amputation (disorder)"
* $SCT#417163006 "Traumatic or non-traumatic injury (disorder)"
* $SCT#242651001 "Injury caused by animal (disorder)"
* $SCT#242490006 "Burning due to contact with hot substance (event)"
* $SCT#133261000119105 "Exposure to potentially hazardous substance (event)"
* $SCT#69129000 "Struck by sharp object (event)"
* $SCT#40947009 "Drowning (event)"
* $SCT#276746005 "Environmental event (event)"
* $SCT#1912002 "Fall (event)"
* $SCT#218100007 "Accident caused by fireworks (event)"
* $SCT#63409001 "Struck by firearm discharge (event)"
* $SCT#212976008 "Asphyxia by strangulation (event)"
* $SCT#52684005 "Assault (event)"
* $SCT#248110007 "Sexual assault (event)"
* $SCT#418161006 "Vehicle accident (event)"
* $SCT#773760007 "Traumatic event (event)"
* $SCT#274215009 "Transport accident (event)"
* $SCT#80943009 "Risk factor (observable entity)"
* $SCT#386812007 "Safety precautions (procedure)"
* $SCT#307836003 "Referral by establishment (procedure)"
* $SCT#118223001 "Patient status finding (finding)"
* $SCT#106167005 "Consciousness related finding (finding)"
* $SCT#148006 "Preliminary diagnosis (contextual qualifier) (qualifier value)"
* $SCT#89100005 "Final diagnosis (discharge) (contextual qualifier) (qualifier value)"
* $SCT#159679004 "Traffic warden (occupation)"
* $SCT#273887006 "Triage index (assessment scale)"
* $SCT#260870009 "Priority (attribute)"
* $SCT#278443006 "Cause of accident type (qualifier value)"
* $SCT#364703007 "Employment detail (observable entity)"
* $SCT#373786007 "Reasons for treatment delay (finding)"
* $SCT#218247007 "Late effect of motor vehicle accident (disorder)"
* $SCT#408919008 "Psychosocial care (regime/therapy)"
* $SCT#360000005 "Closed circuit television (physical object)"
* $SCT#167009006 "Blood ethanol measurement (procedure)"
* $LNC#30976-5 "Date received Form"
* $LNC#69472-9 "Unit responded [Date and time] Vehicle"
* $LNC#69475-2 "Responding unit left the scene with a patient [Date and time] Vehicle"
* $LNC#11288-8 "Arrival time documented"
* $LNC#90123-1 "Response team leader name"
* $LNC#11375-3 "Injury intent"
* $LNC#95376-0 "Type of animal exposed to"
* $LNC#11372-0 "Injury associated activity"
* $LNC#74199-1 "Transferred from another acute care facility [NTDS]"
* $LNC#74286-6 "Transport mode to hospital [NTDS]"
* $LNC#77999-1 "Case notification comment"