ValueSet: SILPH___Element_Terminology__VS_
Id: SILPH-ElementTerminologyVS
Title: "SILPH - Element Terminology (VS)"
Description: "SILPH Value Set for Element Terminology"
* ^meta.versionId = "2"
* ^meta.lastUpdated = "2025-10-29T06:57:32.782+00:00"
* ^url = "http://www.roadsafetyph.doh.gov.ph/ValueSet/SILPH-ElementTerminology"
* ^version = "0.1.0"
* ^status = #draft
* ^contact.telecom.system = #email
* ^expansion.identifier = "urn:uuid:3dd6f1df-4154-431f-b739-7c68590ff6b3"
* ^expansion.timestamp = "2025-10-29T06:57:38+00:00"
* ^expansion.total = 47
* ^expansion.parameter[0].name = "used-codesystem"
* ^expansion.parameter[=].valueUri = "http://www.roadsafetyph.doh.gov.ph/CodeSystem|0.2.0"
* ^expansion.parameter[+].name = "version"
* ^expansion.parameter[=].valueUri = "http://www.roadsafetyph.doh.gov.ph/CodeSystem|0.2.0"
* ^expansion.parameter[+].name = "used-codesystem"
* ^expansion.parameter[=].valueUri = "http://snomed.info/sct|http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.parameter[+].name = "version"
* ^expansion.parameter[=].valueUri = "http://snomed.info/sct|http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.parameter[+].name = "used-codesystem"
* ^expansion.parameter[=].valueUri = "http://loinc.org|2.78"
* ^expansion.parameter[+].name = "version"
* ^expansion.parameter[=].valueUri = "http://loinc.org|2.78"
* ^expansion.parameter[+].name = "displayLanguage"
* ^expansion.parameter[=].valueCode = #en-US,en;q=0.9
* ^expansion.parameter[+].name = "warning-draft"
* ^expansion.parameter[=].valueUri = "http://www.roadsafetyph.doh.gov.ph/CodeSystem|0.2.0"
* ^expansion.parameter[+].name = "warning-draft"
* ^expansion.parameter[=].valueUri = "http://www.roadsafetyph.doh.gov.ph/ValueSet/SILPH-ElementTerminology|0.1.0"
* ^expansion.parameter[+].name = "includeDesignations"
* ^expansion.parameter[=].valueBoolean = false
* ^expansion.contains[0].system = "http://www.roadsafetyph.doh.gov.ph/CodeSystem"
* ^expansion.contains[=].version = "0.2.0"
* ^expansion.contains[=].code = #INJURYFRONT
* ^expansion.contains[=].display = "Site of Injury/Pain - Front Part of Body"
* ^expansion.contains[+].system = "http://www.roadsafetyph.doh.gov.ph/CodeSystem"
* ^expansion.contains[=].version = "0.2.0"
* ^expansion.contains[=].code = #INJURYBACK
* ^expansion.contains[=].display = "Site of Injury/Pain - Back Part of Body"
* ^expansion.contains[+].system = "http://www.roadsafetyph.doh.gov.ph/CodeSystem"
* ^expansion.contains[=].version = "0.2.0"
* ^expansion.contains[=].code = #RRFREMARKS
* ^expansion.contains[=].display = "Run Report Form Remarks"
* ^expansion.contains[+].system = "http://www.roadsafetyph.doh.gov.ph/CodeSystem"
* ^expansion.contains[=].version = "0.2.0"
* ^expansion.contains[=].code = #MVA-COLLISION
* ^expansion.contains[=].display = "FOR TRANSPORT/VEHICULAR ACCIDENT ONLY (Collision; Non-Collision)"
* ^expansion.contains[+].system = "http://www.roadsafetyph.doh.gov.ph/CodeSystem"
* ^expansion.contains[=].version = "0.2.0"
* ^expansion.contains[=].code = #PATIENTVEHICLE
* ^expansion.contains[=].display = "Vehicles Involved: Patient's Vehicle"
* ^expansion.contains[+].system = "http://www.roadsafetyph.doh.gov.ph/CodeSystem"
* ^expansion.contains[=].version = "0.2.0"
* ^expansion.contains[=].code = #OTHERVEHICLE
* ^expansion.contains[=].display = "Other Vehicle/Object Involved (for COLLISION accident ONLY)"
* ^expansion.contains[+].system = "http://www.roadsafetyph.doh.gov.ph/CodeSystem"
* ^expansion.contains[=].version = "0.2.0"
* ^expansion.contains[=].code = #PATIENTPOSITION
* ^expansion.contains[=].display = "Position of Patient"
* ^expansion.contains[+].system = "http://www.roadsafetyph.doh.gov.ph/CodeSystem"
* ^expansion.contains[=].version = "0.2.0"
* ^expansion.contains[=].code = #PLACEOCCURRENCE
* ^expansion.contains[=].display = "Place of Occurrence"
* ^expansion.contains[+].system = "http://www.roadsafetyph.doh.gov.ph/CodeSystem"
* ^expansion.contains[=].version = "0.2.0"
* ^expansion.contains[=].code = #ER_OUTPATIENT_OUTCOME
* ^expansion.contains[=].display = "Outcome"
* ^expansion.contains[+].system = "http://www.roadsafetyph.doh.gov.ph/CodeSystem"
* ^expansion.contains[=].version = "0.2.0"
* ^expansion.contains[=].code = #INPATIENT_OUTCOME
* ^expansion.contains[=].display = "Outcome"
* ^expansion.contains[+].system = "http://www.roadsafetyph.doh.gov.ph/CodeSystem"
* ^expansion.contains[=].version = "0.2.0"
* ^expansion.contains[=].code = #COLLISIONTYPE
* ^expansion.contains[=].display = "Collision Type"
* ^expansion.contains[+].system = "http://www.roadsafetyph.doh.gov.ph/CodeSystem"
* ^expansion.contains[=].version = "0.2.0"
* ^expansion.contains[=].code = #COORDINATIONDONE
* ^expansion.contains[=].display = "Was Transport Coordinated with Receiving Hospital?"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #609328004
* ^expansion.contains[=].display = "Allergic disposition"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #386725007
* ^expansion.contains[=].display = "Body temperature"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #6942003
* ^expansion.contains[=].display = "Level of consciousness"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #3415004
* ^expansion.contains[=].display = "Cyanosis"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #55607006
* ^expansion.contains[=].display = "Problem"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #116154003
* ^expansion.contains[=].display = "Patient"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #399963005
* ^expansion.contains[=].display = "Abrasion"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #125666000
* ^expansion.contains[=].display = "Burn"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #46541008
* ^expansion.contains[=].display = "Second degree burn injury"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #110030002
* ^expansion.contains[=].display = "Concussion injury of brain"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #125667009
* ^expansion.contains[=].display = "Contusion"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #125605004
* ^expansion.contains[=].display = "Fracture of bone"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #423125000
* ^expansion.contains[=].display = "Closed fracture"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #125643001
* ^expansion.contains[=].display = "Open wound"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #417163006
* ^expansion.contains[=].display = "Traumatic or non-traumatic injury"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #242651001
* ^expansion.contains[=].display = "Injury caused by animal"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #1912002
* ^expansion.contains[=].display = "Fall"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #63409001
* ^expansion.contains[=].display = "Struck by firearm discharge"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #52684005
* ^expansion.contains[=].display = "Assault"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #248110007
* ^expansion.contains[=].display = "Sexual assault"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #773760007
* ^expansion.contains[=].display = "Traumatic event"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #260870009
* ^expansion.contains[=].display = "Priority"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #364703007
* ^expansion.contains[=].display = "Employment detail"
* ^expansion.contains[+].system = "http://snomed.info/sct"
* ^expansion.contains[=].version = "http://snomed.info/sct/999991001000101/version/20240701"
* ^expansion.contains[=].code = #218247007
* ^expansion.contains[=].display = "Late effect of motor vehicle accident"
* ^expansion.contains[+].system = "http://loinc.org"
* ^expansion.contains[=].version = "2.78"
* ^expansion.contains[=].code = #30976-5
* ^expansion.contains[=].display = "Date received Form"
* ^expansion.contains[+].system = "http://loinc.org"
* ^expansion.contains[=].version = "2.78"
* ^expansion.contains[=].code = #69472-9
* ^expansion.contains[=].display = "Unit responded [Date and time] Vehicle"
* ^expansion.contains[+].system = "http://loinc.org"
* ^expansion.contains[=].version = "2.78"
* ^expansion.contains[=].code = #69475-2
* ^expansion.contains[=].display = "Responding unit left the scene with a patient [Date and time] Vehicle"
* ^expansion.contains[+].system = "http://loinc.org"
* ^expansion.contains[=].version = "2.78"
* ^expansion.contains[=].code = #11288-8
* ^expansion.contains[=].display = "Arrival time documented"
* ^expansion.contains[+].system = "http://loinc.org"
* ^expansion.contains[=].version = "2.78"
* ^expansion.contains[=].code = #90123-1
* ^expansion.contains[=].display = "Response team leader name"
* ^expansion.contains[+].system = "http://loinc.org"
* ^expansion.contains[=].version = "2.78"
* ^expansion.contains[=].code = #11375-3
* ^expansion.contains[=].display = "Injury intent"
* ^expansion.contains[+].system = "http://loinc.org"
* ^expansion.contains[=].version = "2.78"
* ^expansion.contains[=].code = #95376-0
* ^expansion.contains[=].display = "Type of animal exposed to"
* ^expansion.contains[+].system = "http://loinc.org"
* ^expansion.contains[=].version = "2.78"
* ^expansion.contains[=].code = #11372-0
* ^expansion.contains[=].display = "Injury associated activity"
* ^expansion.contains[+].system = "http://loinc.org"
* ^expansion.contains[=].version = "2.78"
* ^expansion.contains[=].code = #74199-1
* ^expansion.contains[=].display = "Transferred from another acute care facility [NTDS]"
* ^expansion.contains[+].system = "http://loinc.org"
* ^expansion.contains[=].version = "2.78"
* ^expansion.contains[=].code = #74286-6
* ^expansion.contains[=].display = "Transport mode to hospital [NTDS]"
* ^expansion.contains[+].system = "http://loinc.org"
* ^expansion.contains[=].version = "2.78"
* ^expansion.contains[=].code = #77999-1
* ^expansion.contains[=].display = "Case notification comment"
* SILPH_Road_Safety_Local_Codes#INJURYFRONT "Site of Injury/Pain - Front Part of Body"
* SILPH_Road_Safety_Local_Codes#INJURYBACK "Site of Injury/Pain - Back Part of Body"
* SILPH_Road_Safety_Local_Codes#RRFREMARKS "Run Report Form Remarks"
* SILPH_Road_Safety_Local_Codes#MVA-COLLISION "FOR TRANSPORT/VEHICULAR ACCIDENT ONLY (Collision; Non-Collision)"
* SILPH_Road_Safety_Local_Codes#PATIENTVEHICLE "Vehicles Involved: Patient's Vehicle"
* SILPH_Road_Safety_Local_Codes#OTHERVEHICLE "Other Vehicle/Object Involved (for COLLISION accident ONLY)"
* SILPH_Road_Safety_Local_Codes#PATIENTPOSITION "Position of Patient"
* SILPH_Road_Safety_Local_Codes#PLACEOCCURRENCE "Place of Occurrence"
* SILPH_Road_Safety_Local_Codes#ER_OUTPATIENT_OUTCOME "ER/Outpatient Outcome"
* SILPH_Road_Safety_Local_Codes#INPATIENT_OUTCOME "Inpatient Outcome"
* SILPH_Road_Safety_Local_Codes#COLLISIONTYPE "Collision Type"
* SILPH_Road_Safety_Local_Codes#COORDINATIONDONE "Was Transport Coordinated with Receiving Hospital?"
* SNOMED_CT#405796007 "Time of call for help (observable entity)"
* SNOMED_CT#405798008 "Time of arrival of emergency services (observable entity)"
* SNOMED_CT#405799000 "Time of arrival at hospital (observable entity)"
* SNOMED_CT#1269489004 "Chief complaint (observable entity)"
* SNOMED_CT#398099009 "Street address (observable entity)"
* SNOMED_CT#397663001 "Referral source (finding)"
* SNOMED_CT#184096005 "Patient surname (observable entity)"
* SNOMED_CT#184095009 "Patient forename (observable entity)"
* SNOMED_CT#405622006 "Patient middle name (observable entity)"
* SNOMED_CT#397669002 "Age (qualifier value)"
* SNOMED_CT#184100006 "Patient sex (observable entity)"
* SNOMED_CT#734005006 "Telephone number (property) (qualifier value)"
* SNOMED_CT#417662000 "History of clinical finding in subject (situation)"
* SNOMED_CT#513881000000106 "Current medication as reported by patient (observable entity)"
* SNOMED_CT#609328004 "Allergic disposition (finding)"
* SNOMED_CT#86290005 "Respiratory rate (observable entity)"
* SNOMED_CT#248582003 "Rhythm of respiration (observable entity)"
* SNOMED_CT#52653008 "Respiratory sounds (observable entity)"
* SNOMED_CT#78564009 "Heart rate measured at systemic artery (observable entity)"
* SNOMED_CT#364095004 "Pulse rhythm (observable entity)"
* SNOMED_CT#366201008 "Finding of pulse volume (finding)"
* SNOMED_CT#271649006 "Systolic blood pressure (observable entity)"
* SNOMED_CT#271650006 "Diastolic blood pressure (observable entity)"
* SNOMED_CT#386725007 "Body temperature (observable entity)"
* SNOMED_CT#6942003 "Level of consciousness (observable entity)"
* SNOMED_CT#271733001 "Pupil reaction (observable entity)"
* SNOMED_CT#3415004 "Cyanosis (finding)"
* SNOMED_CT#281395000 "Glasgow Coma Score eye opening subscore (observable entity)"
* SNOMED_CT#281397008 "Glasgow Coma Scale verbal response subscore (observable entity)"
* SNOMED_CT#281396004 "Glasgow Coma Scale motor response subscore (observable entity)"
* SNOMED_CT#248241002 "Glasgow coma score (observable entity)"
* SNOMED_CT#55607006 "Problem (finding)"
* SNOMED_CT#119270007 "Management procedure (procedure)"
* SNOMED_CT#397897005 "Paramedic (occupation)"
* SNOMED_CT#159738005 "Ambulanceman (occupation)"
* SNOMED_CT#22515006 "Medical Assistant (occupation)"
* SNOMED_CT#36030000 "Transport vehicle, device (physical object)"
* SNOMED_CT#184107009 "Patient hospital number (observable entity)"
* SNOMED_CT#722248002 "Patient hospital visit number (observable entity)"
* SNOMED_CT#116154003 "Patient (person)"
* SNOMED_CT#184099003 "Date of birth (observable entity)"
* SNOMED_CT#439771001 "Date of event (observable entity)"
* SNOMED_CT#263501003 "Time of onset (observable entity)"
* SNOMED_CT#406543005 "Date of visit (observable entity)"
* SNOMED_CT#406544004 "Time of visit (observable entity)"
* SNOMED_CT#386308007 "First aid (procedure)"
* SNOMED_CT#262519004 "Multiple injuries (disorder)"
* SNOMED_CT#399963005 "Abrasion (disorder)"
* SNOMED_CT#284554003 "Avulsion - injury (disorder)"
* SNOMED_CT#125666000 "Burn (disorder)"
* SNOMED_CT#77140003 "First degree burn injury (morphologic abnormality)"
* SNOMED_CT#46541008 "Second degree burn injury (morphologic abnormality)"
* SNOMED_CT#80247002 "Third degree burn injury (morphologic abnormality)"
* SNOMED_CT#770400008 "Fourth degree burn injury (morphologic abnormality)"
* SNOMED_CT#110030002 "Concussion injury of brain (disorder)"
* SNOMED_CT#125667009 "Contusion (disorder)"
* SNOMED_CT#125605004 "Fracture of bone (disorder)"
* SNOMED_CT#423125000 "Closed fracture of bone (disorder)"
* SNOMED_CT#397181002 "Open fracture (disorder)"
* SNOMED_CT#125643001 "Open wound (disorder)"
* SNOMED_CT#262595009 "Traumatic amputation (disorder)"
* SNOMED_CT#417163006 "Traumatic or non-traumatic injury (disorder)"
* SNOMED_CT#242651001 "Injury caused by animal (disorder)"
* SNOMED_CT#242490006 "Burning due to contact with hot substance (event)"
* SNOMED_CT#133261000119105 "Exposure to potentially hazardous substance (event)"
* SNOMED_CT#69129000 "Struck by sharp object (event)"
* SNOMED_CT#40947009 "Drowning (event)"
* SNOMED_CT#276746005 "Environmental event (event)"
* SNOMED_CT#1912002 "Fall (event)"
* SNOMED_CT#218100007 "Accident caused by fireworks (event)"
* SNOMED_CT#63409001 "Struck by firearm discharge (event)"
* SNOMED_CT#212976008 "Asphyxia by strangulation (event)"
* SNOMED_CT#52684005 "Assault (event)"
* SNOMED_CT#248110007 "Sexual assault (event)"
* SNOMED_CT#418161006 "Vehicle accident (event)"
* SNOMED_CT#773760007 "Traumatic event (event)"
* SNOMED_CT#274215009 "Transport accident (event)"
* SNOMED_CT#80943009 "Risk factor (observable entity)"
* SNOMED_CT#386812007 "Safety precautions (procedure)"
* SNOMED_CT#307836003 "Referral by establishment (procedure)"
* SNOMED_CT#118223001 "Patient status finding (finding)"
* SNOMED_CT#106167005 "Consciousness related finding (finding)"
* SNOMED_CT#148006 "Preliminary diagnosis (contextual qualifier) (qualifier value)"
* SNOMED_CT#89100005 "Final diagnosis (discharge) (contextual qualifier) (qualifier value)"
* SNOMED_CT#159679004 "Traffic warden (occupation)"
* SNOMED_CT#273887006 "Triage index (assessment scale)"
* SNOMED_CT#260870009 "Priority (attribute)"
* SNOMED_CT#278443006 "Cause of accident type (qualifier value)"
* SNOMED_CT#364703007 "Employment detail (observable entity)"
* SNOMED_CT#373786007 "Reasons for treatment delay (finding)"
* SNOMED_CT#218247007 "Late effect of motor vehicle accident (disorder)"
* SNOMED_CT#408919008 "Psychosocial care (regime/therapy)"
* SNOMED_CT#360000005 "Closed circuit television (physical object)"
* SNOMED_CT#167009006 "Blood ethanol measurement (procedure)"
* LOINC#30976-5 "Date received Form"
* LOINC#69472-9 "Unit responded [Date and time] Vehicle"
* LOINC#69475-2 "Responding unit left the scene with a patient [Date and time] Vehicle"
* LOINC#11288-8 "Arrival time documented"
* LOINC#90123-1 "Response team leader name"
* LOINC#11375-3 "Injury intent"
* LOINC#95376-0 "Type of animal exposed to"
* LOINC#11372-0 "Injury associated activity"
* LOINC#74199-1 "Transferred from another acute care facility [NTDS]"
* LOINC#74286-6 "Transport mode to hospital [NTDS]"
* LOINC#77999-1 "Case notification comment"